;;; drm-editing.el -*- lexical-binding: t; -*-

(show-paren-mode 1)
(electric-pair-mode 1)

(straight-use-package 'ws-butler)
(straight-use-package 'evil-nerd-commenter)
(straight-use-package 'smartparens)
(straight-use-package 'meow)

;; Set up ws-butler for trimming whitespace and line endings
(add-hook 'text-mode-hook 'ws-butler-mode)
(add-hook 'prog-mode-hook 'ws-butler-mode)

;; meow mode
(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-overwrite-define-key
   '("k" . meow-next)
   '("l" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; SPC j/k will run the original command in MOTION state.
   '("k" . "H-k")
   '("l" . "H-l")
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '("\\" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("j" . meow-left)
   '("J" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("k" . meow-next)
   '("K" . meow-next-expand)
   '("l" . meow-prev)
   '("L" . meow-prev-expand)
   '(";" . meow-right)
   '(":" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))

(require 'meow)
(meow-setup)
(meow-global-mode 1)

;; Set a global binding for better line commenting/uncommenting
(global-set-key (kbd "C-c ;") 'evilnc-comment-or-uncomment-lines)
;; Set other global bindings that make life easier
(global-set-key (kbd "C-c w w") 'other-window)
(global-set-key (kbd "C-c w o") 'delete-other-windows)
(global-set-key (kbd "C-c w k") 'delete-window)
(global-set-key (kbd "C-c w h") 'split-window-right)
(global-set-key (kbd "C-c w v") 'split-window-below)
(global-set-key (kbd "C-c b b") 'consult-buffer)
(global-set-key (kbd "C-c b k") 'kill-buffer)
(global-set-key (kbd "C-c b w") 'kill-buffer-and-window)
(global-set-key (kbd "C-c b l") 'buffer-list)
(global-set-key (kbd "C-c f f") 'other-frame)
(global-set-key (kbd "C-c f o") 'delete-other-frames)
(global-set-key (kbd "C-c f k") 'delete-frame)
(global-set-key (kbd "C-c f b") 'consult-buffer-other-frame)
(global-set-key (kbd "C-c f n") 'make-frame-command)
(global-set-key (kbd "C-c f c") 'other-frame-prefix)
(global-set-key (kbd "C-c f p") 'project-other-frame-command)
(global-set-key (kbd "C-c p p") 'project-switch-project)
(global-set-key (kbd "C-c p b") 'consult-project-buffer)
(global-set-key (kbd "C-c p g") 'magit-status)
(global-set-key (kbd "C-c p k") 'project-kill-buffers)
(global-set-key (kbd "C-c p e") 'project-eshell)
(global-set-key (kbd "C-c p s") 'project-shell)
(global-set-key (kbd "C-c p d") 'project-find-dir)
(global-set-key (kbd "C-c p f") 'project-find-file)
(global-set-key (kbd "C-c p G") 'project-find-regexp)
(global-set-key (kbd "C-c p r") 'project-query-replace-regexp)
(global-set-key (kbd "C-c p D") 'project-dired)

(setq org-export-allow-bind-keywords t)

(provide 'drm-editing)
